# Build settings
markdown: redcarpet
highlighter: pygments

# Enable footnotes.
redcarpet:
  extensions: [footnotes]

# Site settings
title: "KernelPicnic"
description: ""

email: peter.adkins@kernelpicnic.net
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Peter Adkins'
author: 'Peter Adkins'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "//darkarnium.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/darkarnium
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/darkarnium
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: youtube
    url:  https://www.youtube.com/channel/UCc0My6KF569yM6UdxHt903A
    desc: Follow me on YouTube
    share_url:
    share_title:
    share_link:
